### ISSUE TITLE
How to download this game?

### ISSUE THREAD

**Issue by maxCodeVector** [Instein98/SustechMonopoly#1]
I want to play this game but I don't know where I can download this link? And I am afraid maybe I need to the IOS version. Could you please kindly give me the download link, both android or IOS? I suggest you could push them in your read me file...

**Comment by Instein98** [comment]
If you go to the "release" you can find the executable. I do not have any usable IOS releases because I do not have a Mac. The previous build for IOS is from Bohao and that is for the old server which has been abandoned.

**Comment by maxCodeVector** [comment]
why not go to store and buy one?



---Original---

**Comment by Instein98** [comment]
You can buy me one and I will be happy.
